=== AleksaJackson/Provera_Znanja/Provera_Znanja/magacinDTD.dtd
<!ELEMENT Artikli (Artikal)>
<!ELEMENT Artikal (Naziv,DatumIzrade,Cena,KompanijaProdavca,EmailProdavca)>
<!ELEMENT Naziv (#PCDATA)>
<!ATTLIST Naziv id CDATA #REQUIRED>
<!ELEMENT DatumIzrade (Dan,Mesec,Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT Cena tip (din|eur) "din">
<!ELEMENT DatumIzrade (ImeKompanije,Adresa)>
<!ELEMENT ImeKompanije (#PCDATA)>
<!ELEMENT Adresa (#PCDATA)+>
<!ELEMENT EmailProdavca (#PCDATA)+>
<!ELEMENT Cena tip (privatni|sluzbeni) #REQUIRED>

=== AleksaJackson/Provera_Znanja/Provera_Znanja/magacin.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Artikli SYSTEM "magacinDTD.dtd" >
<Artikli>
	<Artikal>
		<Naziv id="1">PVC</Naziv>
		<DatumIzrade>
			<Dan>5</Dan>
			<Mesec>4</Mesec>
			<Godina>2020</Godina>
		</DatumIzrade>
		<Cena tip="din">25000</Cena>
		<KompanijaProdavca>
			<ImeKompanije>Aleksa</ImeKompanije>
			<Adresa>Ivankovacka 5</Adresa>
		</KompanijaProdavca>
		<EmailProdavca tip="privatni">milinkovic.aleksa@gmail.com</EmailProdavca> 	
	</Artikal>
<Artikli>
